name: Merge to main push build number to ECR

on:
  push:
    branches: main
    paths-ignore:
      - 'chart/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Check running containers
        run: docker-compose -f docker-compose.test.yml ps

      - name: Check logs
        run: docker-compose -f docker-compose.test.yml logs defaults

      - name: Run test suite
        run: pip install -r requirements_dev.txt && python -m pytest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: icon-network-exporter
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update dev deployment values file and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'chart/deployments/dev/values.dev.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.run_number }}
          branch: main
          targetBranch: main
          createPR: 'false'
          message: 'Update dev deployment image version to ${{ github.run_number }}'
          token: ${{ secrets.GITHUB_TOKEN }}
